// 「회식하는 동물들」 에피소드. 컷은 510x565 좌표.
// bubbles: {t, x, y, w, type: say|shout|think|msg|sfx, from(msg 보낸 사람), tail: l|r|c}
window.SERIES = "회식하는 동물들";
window.EPISODES = [
  {
    id: "ep1", title: "소맥 황금비율", who: "김대리",
    panels: [
      { bg: "pocha", narr: "금요일 밤 9시, 회식",
        chars: [{ k: "dog", e: "happy", x: 170, y: 290, s: 0.95, prop: "somac" }, { k: "bear", e: "happy", x: 390, y: 320, s: 0.82, anim: "bob" }],
        bubbles: [{ t: "황금비율 소맥\n나왔습니다~!", x: 24, y: 70, w: 230, tail: "c" }, { t: "역시 김대리!", x: 300, y: 140, w: 180, tail: "c" }] },
      { bg: "pocha",
        chars: [{ k: "dog", e: "happy", x: 255, y: 300, s: 1.0, prop: "phone" }],
        bubbles: [{ t: "띠링♪", x: 330, y: 230, type: "sfx" }, { from: "여친", t: "우리… 그만하자", x: 40, y: 60, w: 300, type: "msg" }] },
      { bg: "pocha",
        chars: [{ k: "dog", e: "shock", x: 255, y: 310, s: 1.05, prop: "phone", anim: "shake" }],
        bubbles: [{ t: "…네?!", x: 150, y: 50, w: 210, type: "shout", tail: "c" }] },
      { bg: "pocha",
        chars: [{ k: "dog", e: "cry", x: 200, y: 300, s: 1.0, prop: "soju", anim: "shake" }, { k: "bear", e: "shock", x: 420, y: 330, s: 0.7, anim: "bob" }],
        bubbles: [{ t: "소맥 비율은 맞췄는데…\n우리 비율은 안 맞았나 봐요", x: 20, y: 40, w: 330, tail: "l" }] },
    ],
  },
  {
    id: "ep2", title: "다시는 안 마신다", who: "박과장",
    panels: [
      { bg: "bedroom", narr: "월요일 아침 7시",
        chars: [{ k: "cat", e: "hungover", x: 230, y: 330, s: 1.0, blanket: "body", anim: "bob" }],
        bubbles: [{ t: "따르릉!! ×5", x: 300, y: 200, type: "sfx" }, { t: "다시는…\n안 마신다…", x: 30, y: 70, w: 210, tail: "c" }] },
      { bg: "office", narr: "해장국 앞에서 영혼 이탈 중",
        chars: [{ k: "cat", e: "hungover", x: 255, y: 330, s: 0.95, prop: "bowl", soul: true, anim: "sway" }],
        bubbles: [{ t: "……", x: 330, y: 160, w: 120, tail: "l" }] },
      { bg: "office",
        chars: [{ k: "bear", e: "happy", x: 160, y: 300, s: 0.95 }, { k: "cat", e: "shock", x: 400, y: 340, s: 0.75, anim: "shake" }],
        bubbles: [{ t: "오늘 저녁\n회식이다~!", x: 30, y: 60, w: 220, type: "shout", tail: "c" }] },
      { bg: "pocha", narr: "(오늘 아침에 한 말: 다시는 안 마신다)",
        chars: [{ k: "cat", e: "drunk", x: 255, y: 310, s: 1.0, prop: "somac", anim: "sway" }],
        bubbles: [{ t: "딱… 한 잔만…", x: 120, y: 100, w: 260, tail: "c" }] },
    ],
  },
  {
    id: "ep3", title: "인생 첫 회식", who: "막내 햄찡",
    panels: [
      { bg: "pocha", narr: "막내 햄찡, 인생 첫 회식",
        chars: [{ k: "hamster", e: "normal", x: 170, y: 320, s: 0.9, prop: "beer" }, { k: "bear", e: "happy", x: 400, y: 320, s: 0.82 }],
        bubbles: [{ t: "저 술 잘\n못 마셔요…", x: 20, y: 90, w: 200, tail: "c" }, { t: "한 잔만 해~", x: 300, y: 150, w: 180, tail: "c" }] },
      { bg: "pocha", narr: "한 잔 후",
        chars: [{ k: "hamster", e: "drunk", x: 255, y: 310, s: 1.05, prop: "beer", anim: "sway" }],
        bubbles: [{ t: "딸꾹!", x: 340, y: 150, type: "sfx" }] },
      { bg: "karaoke",
        chars: [{ k: "hamster", e: "happy", x: 255, y: 330, s: 1.0, prop: "mic", anim: "sway" }],
        bubbles: [{ t: "제 노래\n들어주세요!!!", x: 110, y: 170, w: 290, type: "shout", tail: "c" }] },
      { bg: "karaoke", narr: "3시간 후",
        chars: [{ k: "dog", e: "sleep", x: 80, y: 430, s: 0.5, anim: "bob" }, { k: "cat", e: "sleep", x: 430, y: 430, s: 0.5, anim: "bob" }, { k: "bear", e: "sleep", x: 160, y: 470, s: 0.45, anim: "bob" }, { k: "hamster", e: "happy", x: 290, y: 330, s: 0.95, prop: "mic", anim: "sway" }],
        bubbles: [{ t: "앵콜!!\n한 곡만 더!!", x: 230, y: 170, w: 240, type: "shout", tail: "l" }] },
    ],
  },
  {
    id: "ep4", title: "딱 한 잔만", who: "김대리 · 박과장",
    panels: [
      { bg: "office", narr: "저녁 7시",
        chars: [{ k: "dog", e: "happy", x: 160, y: 310, s: 0.9 }, { k: "cat", e: "normal", x: 380, y: 320, s: 0.88 }],
        bubbles: [{ t: "과장님, 딱 한 잔만\n하고 가요~", x: 20, y: 70, w: 260, tail: "c" }, { t: "딱 한 잔!", x: 330, y: 150, w: 150, tail: "c" }] },
      { bg: "pocha", narr: "밤 11시",
        chars: [{ k: "dog", e: "drunk", x: 160, y: 310, s: 0.9, prop: "soju", anim: "sway" }, { k: "cat", e: "drunk", x: 380, y: 320, s: 0.88, prop: "somac", anim: "sway" }],
        bubbles: [{ t: "딱 한 병만 더…", x: 110, y: 110, w: 280, tail: "c" }] },
      { bg: "karaoke", narr: "새벽 2시",
        chars: [{ k: "dog", e: "drunk", x: 140, y: 340, s: 0.85, prop: "mic", anim: "sway" }, { k: "cat", e: "drunk", x: 370, y: 350, s: 0.85, anim: "sway" }],
        bubbles: [{ t: "3차 가즈아!!", x: 120, y: 175, w: 270, type: "shout", tail: "c" }] },
      { bg: "store", narr: "새벽 4시, 편의점 앞",
        chars: [{ k: "dog", e: "hungover", x: 160, y: 330, s: 0.88, prop: "ramen", anim: "bob" }, { k: "cat", e: "hungover", x: 370, y: 335, s: 0.85, prop: "ramen", anim: "bob" }],
        bubbles: [{ t: "…분명 딱 한 잔이었는데", x: 70, y: 150, w: 370, tail: "c" }] },
    ],
  },
  {
    id: "ep5", title: "월요일 아침 단톡방", who: "김대리",
    panels: [
      { bg: "bedroom", narr: "다음 날 아침",
        chars: [{ k: "dog", e: "sleep", x: 230, y: 330, s: 1.0, blanket: "body", anim: "bob" }],
        bubbles: [{ t: "카톡! 카톡! 카톡!", x: 220, y: 180, type: "sfx" }] },
      { bg: "bedroom",
        chars: [{ k: "dog", e: "normal", x: 255, y: 320, s: 1.0, prop: "phone", blanket: "body" }],
        bubbles: [{ from: "곰 부장님", t: "김대리 어제 노래 잘하던데 ^^", x: 30, y: 50, w: 400, type: "msg" }] },
      { bg: "dark", narr: "어제 기억: 없음",
        chars: [{ k: "dog", e: "shock", x: 255, y: 320, s: 1.05, anim: "shake" }],
        bubbles: [{ t: "제가… 무슨 노래를…?", x: 90, y: 90, w: 330, type: "think", tail: "c" }] },
      { bg: "bedroom", narr: "김대리, 오늘 연차 씁니다",
        chars: [{ k: "dog", e: "cry", x: 255, y: 285, s: 1.05, blanket: "head", anim: "shake" }],
        bubbles: [{ from: "막내 햄찡", t: "부장님한테 '사랑해요' 세 번 하셨어요", x: 20, y: 60, w: 470, type: "msg" }] },
    ],
  },
];
